'use strict';
let token='',offset=0,currentChat=null;const $=id=>document.getElementById(id);
const show=(id,v)=>{$(id).textContent=typeof v==='string'?v:JSON.stringify(v,null,2)};
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(`${r.status} ${data.error} · ${data.request_id||''}`);return data}
function button(text,fn,cls=''){const b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=()=>act(fn,b);return b}
async function act(fn,b){if(b)b.disabled=true;try{await fn();show('notice','操作完成，数据已由后端返回。')}catch(e){show('notice',e.message)}finally{if(b)b.disabled=b.id==='continue' && currentChat?.status!=='awaiting_approval'}}
async function refresh(){const data=await api('overview?offset='+offset);show('identity',`${data.identity.user} / 租户 ${data.identity.tenant} / ${data.identity.role}`);show('connection','已连接 · '+data.identity.tenant);show('policy-info',data.policy);show('audit-list',data.audit);show('page','第 '+(offset/50+1)+' 页');$('chat-list').replaceChildren();for(const chat of data.chats||[]){$('chat-list').append(button(chat.id.slice(0,8)+' · '+chat.status,async()=>{renderChat(await api('chat?id='+encodeURIComponent(chat.id)))},'secondary'))}$('approval-list').replaceChildren();for(const a of data.approvals){const el=document.createElement('div');el.className='card';const title=document.createElement('strong');title.textContent=a.tool+' · '+a.status;const p=document.createElement('pre');p.textContent=JSON.stringify({params:JSON.parse(a.params),digest:a.digest,expires:new Date(a.expires*1000).toISOString()},null,2);el.append(title,p);if(a.status==='pending')el.append(button('确认以上参数并执行',async()=>{const result=await api('approve',{action_id:a.id,digest:a.digest});show('answer',result);await refresh()}));$('approval-list').append(el)}if(!data.approvals.length)show('approval-list','当前没有审批记录。');$('run-list').replaceChildren();for(const r of data.runs){const tr=document.createElement('tr');for(const k of ['id','agent','status','steps']){const td=document.createElement('td');td.textContent=r[k];tr.append(td)}const td=document.createElement('td');if(r.status==='running')td.append(button('取消',async()=>{await api('cancel',{run_id:r.id});await refresh()},'secondary'));tr.append(td);$('run-list').append(tr)}$('tool-list').replaceChildren();for(const t of data.tools){const p=document.createElement('pre');p.textContent=`${t.name}\n${t.action} · ${t.risk}\n超时 ${t.timeout_ms}ms · 副作用 ${t.side_effect}`;$('tool-list').append(p)}}
$('connect').onclick=()=>act(async()=>{token=$('token').value.trim();$('token').value='';const cap=await api('capabilities');$('mode').value=cap.local_model?'local':'mock';modeHelp(cap.local_model);await refresh()},$('connect'));
$('refresh').onclick=()=>act(refresh,$('refresh'));
$('execute').onclick=()=>act(async()=>{show('answer','正在执行，请稍候。本地模型首次加载可能较慢。');if($('mode').value==='local'){renderChat(await api('chat',{task:$('task').value}))}else{show('answer',await api('agent',{task:$('task').value}))}await refresh()},$('execute'));
$('revoke').onclick=()=>act(async()=>{if(!confirm('撤销当前身份，后续访问将返回 401。确认继续？'))return;await api('revoke',{});token='';show('connection','身份已撤销');show('answer','后续调用已被阻止。')},$('revoke'));
$('prev').onclick=()=>act(async()=>{offset=Math.max(0,offset-50);await refresh()});$('next').onclick=()=>act(async()=>{offset+=50;await refresh()});

function renderChat(c){currentChat=c;show('answer',c.answer||c.status);show('transcript',c.messages);$('continue').disabled=c.status!=='awaiting_approval';$('reload-chat').disabled=false}
function modeHelp(available){show('mode-help',available?'本地模型已配置：可以输入自然语言，读取数据、提出修改，并在审批后继续回答。':'本地模型未配置。当前为固定命令测试模式；按本地模型文档启动后重新连接。');if(!available)$('task').value='read-doc doc-1'}
$('continue').onclick=()=>act(async()=>{if(!currentChat)return;show('answer','正在读取已批准的执行结果并生成回答…');renderChat(await api('chat/resume',{chat_id:currentChat.id}));await refresh()},$('continue'));
$('reload-chat').onclick=()=>act(async()=>{if(currentChat)renderChat(await api('chat?id='+encodeURIComponent(currentChat.id)));await refresh()});
$('mode').onchange=()=>{$('task').value=$('mode').value==='local'?'请读取 doc-1 文档并用中文概括内容。':'read-doc doc-1'};
